### PR TITLE
Made some UI enhancements

### PR DESCRIPTION
**Pull request by varunpusarla**
image

### CODE REVIEW

**Comment by varunpusarla** [comment]
@SuyashSonawane  @tejasmorkar  Guys can you please review this and merge ?

**Review by nupur-shiturkar — APPROVED** [review]
Looks good!

**Comment by varunpusarla** [comment]
Thanks @nupur-shiturkar

**Comment by tejasmorkar** [comment]
Which issue is this PR related to @varunpusarla

**Comment by varunpusarla** [comment]
This PR was for issue #20 .

**Comment by tejasmorkar** [comment]
No one was assigned to issue #20 

These changes were not needed. The heading doesn't match the theme. 
Please follow the contribution guidelines and start working on issues only after you have been assigned to them by one of the maintainers.

**Pull request closed without merging**
